name: Linux tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux-py:
    name: Linux py${{ matrix.python }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install python dependencies
        run: python -m pip install tox codecov
      - name: Run python tests
        run: tox
      - name: Run pre commit checks
        uses: pre-commit/action@v3.0.0
