name: Linux tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux-py:
    name: Linux py${{ matrix.python }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.python }}-pip-${{ hashFiles('**/setup.py') }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install python dependencies
        run: python -m pip install tox codecov
      - name: Run python tests
        run: tox
      - name: Run pre commit checks
        uses: pre-commit/action@v2.0.3
